name: Deploy Site

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'
      - 'vite.config.ts'
      - '.github/workflows/deploy-articles.yml'
      - 'tsconfig.json'
      - 'tailwind.config.js'
      - '*.css'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci
          if [ $? -ne 0 ]; then
            echo "npm install failed"
            exit 1
          fi

      - name: Build Project
        run: |
          echo "Starting build process..."
          npm run build
          if [ $? -ne 0 ]; then
            echo "build failed"
            exit 1
          fi
          echo "Build completed successfully"

      - name: Verify Build Output
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          
          echo "\nChecking build structure:"
          find dist/ -type f -exec ls -l {} \;

      - name: Copy .htaccess Files
        run: |
          echo "Copying .htaccess files..."
          cp -v public/.htaccess dist/
          
          echo "\nVerifying .htaccess files:"
          if [ -f "dist/.htaccess" ]; then
            cat dist/.htaccess
          else
            echo "Root .htaccess is missing!"
          fi

      - name: Deploy to GoDaddy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: m3labs.co.uk
          username: info@m3labs.co.uk
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          security: loose
          local-dir: ./dist/
          server-dir: /home/ls88d69thfvm/public_html/
          state-name: .ftp-deploy-sync-state.json
          dry-run: false
          dangerous-clean-slate: false
          timeout: 120000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store

      - name: Verify Site Accessibility
        run: |
          echo "Verifying site deployment..."
          # Check main site
          MAIN_STATUS=$(curl -sL -w "%{http_code}" https://m3labs.co.uk -o /dev/null)
          echo "Main site status: $MAIN_STATUS"
          if [ "$MAIN_STATUS" != "200" ]; then
            echo "Error: Main site returned status $MAIN_STATUS"
            exit 1
          fi
          
          # Check a specific article (using the test article)
          echo "Verifying article access..."
          ARTICLE_STATUS=$(curl -sL -w "%{http_code}" https://m3labs.co.uk/content/articles/github-actions-test.md -o /dev/null)
          echo "Article status: $ARTICLE_STATUS"
          if [ "$ARTICLE_STATUS" != "200" ]; then
            echo "Warning: Article returned status $ARTICLE_STATUS"
            # Don't exit with error as the article might be cached/processing
          fi 