name: Deploy Articles

on:
  push:
    paths:
      - 'public/content/articles/**'
      - 'public/.htaccess'
      - 'src/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add timeout to prevent hanging
    steps:
      - uses: actions/checkout@v3  # Update to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Update to v3
        with:
          node-version: '18'
          cache: 'npm'  # Enable npm caching

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GoDaddy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4  # Switch to a more maintained FTP action
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./dist/
          server-dir: ./
          dangerous-clean-slate: false
          timeout: 600000  # 10 minute timeout
          protocol: ftp

      - name: Deploy .htaccess
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./public/
          server-dir: ./
          dangerous-clean-slate: false
          timeout: 600000
          protocol: ftp 