name: Deploy Site

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'
      - 'vite.config.ts'
      - '.github/workflows/deploy-articles.yml'
      - 'tsconfig.json'
      - 'tailwind.config.js'
      - '*.css'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci
          if [ $? -ne 0 ]; then
            echo "npm install failed"
            exit 1
          fi

      - name: Build Project
        run: |
          echo "Starting build process..."
          npm run build
          if [ $? -ne 0 ]; then
            echo "build failed"
            exit 1
          fi
          echo "Build completed successfully"

      - name: Debug Build Output
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "\nFull directory structure:"
          find dist/ -type f
          echo "\nChecking file sizes:"
          du -h dist/

      - name: Copy .htaccess Files
        run: |
          echo "Copying .htaccess files..."
          cp -v public/.htaccess dist/
          
          echo "\nVerifying .htaccess files:"
          if [ -f "dist/.htaccess" ]; then
            cat dist/.htaccess
          else
            echo "Root .htaccess is missing!"
          fi

      - name: Deploy to GoDaddy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: m3labs.co.uk
          username: info@m3labs.co.uk
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          security: loose
          local-dir: ./dist/
          server-dir: /public_html/
          state-name: .ftp-deploy-sync-state.json
          dry-run: false
          dangerous-clean-slate: true
          timeout: 120000
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store

      - name: Verify Deployment
        run: |
          echo "Waiting for changes to propagate..."
          sleep 15
          
          echo "Verifying deployment..."
          echo "\nChecking main page:"
          curl -sI https://m3labs.co.uk/ | grep -E "HTTP|Content-Type|Cache-Control"
          
          echo "\nChecking assets:"
          for file in dist/assets/*; do
            filename=$(basename "$file")
            echo "Checking $filename"
            curl -sI "https://m3labs.co.uk/assets/$filename" | grep -E "HTTP|Content-Type"
          done
          
          echo "\nChecking content files:"
          for file in dist/content/articles/*.md; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              echo "Checking $filename"
              curl -sI "https://m3labs.co.uk/content/articles/$filename" | grep -E "HTTP|Content-Type"
            fi
          done 