name: Deploy to GoDaddy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Add .htaccess
        run: |
          cp public/.htaccess dist/
          echo "Build contents:"
          ls -la dist/

      - name: Deploy to GoDaddy
        uses: SamKirkland/FTP-Deploy-Action@v2.0.0
        with:
          server: ftp.m3labs.co.uk
          username: m3amir@m3labs.co.uk	
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./dist/
          server-dir: /public_html/
          dangerous-clean-slate: true
          timeout: 60000

      - name: Verify Deployment
        run: |
          echo "Waiting for changes to propagate..."
          sleep 5
          
          echo "Checking site status..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://m3labs.co.uk)
          echo "Site status: $STATUS"
          
          if [ "$STATUS" != "200" ]; then
            echo "Warning: Site returned status $STATUS"
          else
            echo "Site is accessible!"
          fi
