name: Deploy Articles

on:
  push:
    paths:
      - 'public/content/articles/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to GoDaddy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './public/content/articles/*'
          remote_path: '/public/content/articles/'
          sftpArgs: '-o StrictHostKeyChecking=no' 