name: Deploy Vite React TS to GoDaddy

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: m3labs.co.uk
          username: ls88d69thfvm
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21  # SFTP typically uses port 22
          protocol: ftps
          local-dir: "dist/"  # Deploy only the built files
          server-dir: "/home/ls88d69thfvm/public_html/"  # Adjust if your site is inside a subfolder
