name: Deploy Articles

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'vite.config.ts'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          if [ $? -ne 0 ]; then
            echo "npm install failed"
            exit 1
          fi

      - name: Build Project
        run: |
          npm run build
          if [ $? -ne 0 ]; then
            echo "build failed"
            exit 1
          fi

      - name: List dist directory
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of dist/content/articles:"
          mkdir -p dist/content/articles
          cp -r src/content/articles/* dist/content/articles/
          ls -la dist/content/articles/

      - name: Deploy to GoDaddy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.m3labs.co.uk
          username: info@m3labs.co.uk
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          security: loose
          local-dir: ./dist/
          server-dir: /home/ls88d69thfvm/public_html/
          state-name: .ftp-deploy-sync-state.json
          dry-run: false
          dangerous-clean-slate: true
          timeout: 120000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/** 